// <auto-generated />
namespace NetApp.Migrations.Project
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TactsCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TactsCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201909300522513_Tacts Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
